# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14247139da46d4fdf13d2dbde42e6cead7085d791d5abc55510797f2794ceebe0ea6dcde8608351fe0b02cf40e194ac2ee0fc27610fa5021785d0c8230ec3020

test:
  secret_key_base: 847507a0cfe7a88061ba6316df5e189b3c651af5144d335af88fa7ac1d6c429b36bd2ff52d08b2552c7a48d1984e9508e826ae6a636a689be24694b49b1941f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
